### ISSUE TITLE
Queuejobs do not have error messages when they fail (to be applied)

### ISSUE THREAD

**Issue by maartenjanvangool** [GijsvanDulmen/k8qu#10]
My queuejob did not apply the resource due to the lack of privileges (it was not allowed to deploy pods). 

It would be nice if I could see that if I query the queuejob.

**Comment by GijsvanDulmen** [comment]
Should be fixed with https://github.com/GijsvanDulmen/k8qu/commit/e335c80119323b8aab98d77b6ddf65bb12119f51
